-- Plot
workspace.Plots.Plot3 -- OwnerUserId

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.PickupSpinner
Event:FireServer(
    workspace.Plots.Plot1.PlayerSpinners.Spinner3 -- Tier
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.DropSpinner
Event:FireServer(
    nil,
    2, -- TileIndex -- workspace.Plots.Plot1.Grids.MergeGrids:GetChildren()[6]
    "Merge"
)



-- Buy Spinner --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.BuyMaxSpinner
Event:FireServer()


-- Rebirth --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.Rebirth
Event:FireServer()
