-- Auto Flip --
getgenv().Flipping = not getgenv().Flipping
while getgenv().Flipping do
task.wait()
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.Click
Event:FireServer()
end

-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Rebirth.Container.Background.Content.ClaimBtn
game:GetService("Players").LocalPlayer.PlayerGui.Rebirth.Container.Background.Content.Bar.CanvasGroup.InsideBar.Position.X.Scale >= 0

-- auto critical --
game:GetService("Players").LocalPlayer.PlayerGui.CritUI
