--[[
workspace["4"]["玩家区域"]["玩家区域"].Touch
-- plot is LocalPlayer FishShowPlotId attribute 

-- click
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remote.Event.Level["[C-S]Click"]
Event:FireServer(
    59 -- index
)


-- hit
workspace["主场景"]["关卡4"]["水面"] -- target
workspace["主场景"]["关卡4"]["光门"] -- check CanCollide

-- upgrade --
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame["1"]["1"].Sell.go
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame["1"]["1"].Flame.name

-- rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Main["Rebirth+1water"].UI1
game:GetService("Players").LocalPlayer.PlayerGui.Main["Rebirth+1water"].UI1["Progress bar"]["Internal progress bar"]
game:GetService("Players").LocalPlayer.PlayerGui.Main["Rebirth+1water"].UI1.RebirthButton.TextButton
]]
