game:GetService("Players").LocalPlayer.PlayerGui.Main.Container.Frames.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.Main.Container.Frames.Rebirth.Bar.CanvasGroup.Filler
game:GetService("Players").LocalPlayer.PlayerGui.Main.Container.Frames.Rebirth.ProductHolders.Purchaseyes


-- wins --
workspace.Stages
workspace.Stages.Stage5.Wall
workspace.Stages.Stage5.ClaimWins.Main
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.KickBall
Event:FireServer()
