-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.ScreamClicked
Event:FireServer()




game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.Rebirth


game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.Rebirth.Main.FillBar.Bar
game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.Rebirth.Main.Rebirth
