-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.RebirthService.RF.TryRebirth
local Result = table.pack(Event:InvokeServer())

local ExpectedResult = table.unpack({
    false,
    "You are doing this too quickly! \xE2\x9D\x8C"
})
game:GetService("Players").LocalPlayer.PlayerGui.Rebirth.Frame.Container.RebirthBtn
game:GetService("Players").LocalPlayer.PlayerGui.Rebirth.Frame.Container.Bar.Fill

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.PickaxeService.RF.TryDamage
Event:Inv--okeServer(
    2, -- Pickaxe index,
    "1",
    "c9b9fb352afd47e0b8ec8232408b6f0c" -- pet id -- workspace.CASCHES.CLIENT_ITEMS["734c127a724741849ecf2589058e2f24"]
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.PickaxeService.RF.TryDamage
local Result = table.pack(Event:InvokeServer(
    1,
    "1",
    "2a076d309295418b9b6f291dc5c4c9b7"
))

local ExpectedResult = table.unpack({
    true,
    2,
    false,
    2,
    false
})


-- place best animal --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.SlotService.RF.TryPlaceBest
Event:InvokeServer()


-- collect cash --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.SlotService.RF.TryCollectCurrency
Event:InvokeServer()


-- upgrade --
main upgrade and pen skin

-- animal --
-- denied --
game:GetService("Players").LocalPlayer.PlayerGui.StoredItems.Frame.Container.Template

-- access --
game:GetService("Players").LocalPlayer.PlayerGui.StoredItems.Frame.Container["6528105ea6124b2b8523a0d06a089491"].Buttons.Upgrade

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.SlotService.RF.TryUpgradeItem
Event:InvokeServer(
    "24729ec8a8294b4a98d3614a90f5897f"
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.PickaxeService.RF.TryDamage
local Result = table.pack(Event:InvokeServer(
    1,
    "1",
    "2a076d309295418b9b6f291dc5c4c9b7"
))
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.PickaxeService.RF.TryDamage
local Result = table.pack(Event:InvokeServer(
    1,
    "1",
    "2a076d309295418b9b6f291dc5c4c9b7"
))




-- need rendah to tinggi


-- buy Pickaxe --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.PickaxeService.RF.TryPurchase
Event:InvokeServer(
    "Iron" -- game:GetService("Players").LocalPlayer.PlayerGui.PickaxeShop.Frame.Container.Iron
)

-- access --
game:GetService("Players").LocalPlayer.PlayerGui.PickaxeShop.Frame.Container.Wood.Buttons.Currency

-- ignore --
game:GetService("Players").LocalPlayer.PlayerGui.PickaxeShop.Frame.Container.Wood.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.PickaxeShop.Frame.Container.Diamond.Buttons.Action

-- buy food --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.BoostService.RF.TryPurchase
Event:InvokeServer(
    "ClearingFood" -- game:GetService("Players").LocalPlayer.PlayerGui.BoostShop.Frame.Container.ClearingFood
)

game:GetService("Players").LocalPlayer.PlayerGui.BoostShop.Frame.Container.ClearingFood
game:GetService("Players").LocalPlayer.PlayerGui.BoostShop.Frame.Container.ClearingFood.Stock.Text == "STOCK: 0

-- auto sell --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.ItemService.RF.TrySell
Event:InvokeServer()

-- Codes --
-- DISCO
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Library.Knit.Knit.Services.CodeService.RF.TryRedeem
Event:InvokeServer(
    "DISCO"
) 
