game:GetService("Players").LocalPlayer.PlayerGui.IncomeSource.Container.Upgrade.Holder.TextButton

-- click --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.IncomeSource
Event:FireServer(
    "Basic_Stand"
)
workspace.Game.Plots["4"].Buttons.Basic_Stand


-- buy button --
workspace.Game.Plots["4"].OccupiedBy.Value
workspace.Game.Plots["4"].Buttons
workspace.Game.Plots["4"].Buttons.Basic_Stand.Tips_Jar.Touch
workspace.Game.Plots["4"].Buttons.Basic_Stand.Cone_Stand.Touch

-- phone --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

-- waiting
local Event = game:GetService("ReplicatedStorage").Events.Phone
firesignal(Event.OnClientEvent)
-- call
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt
local Event = game:GetService("ReplicatedStorage").Events.Phone
Event:FireServer(
    "Accept",
    0
)
