-- Game Name: Unbox ASMR
workspace.Plots.ActivePlots 
workspace.Plots.ActivePlots.Plot1 -- OwnerUserId

-- Auto ASMR --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").ASMRRewardRemotes.RequestInteraction
Event:FireServer(
    workspace.Plots.ActivePlots.Plot1.ASMR.Placed_CHOCOLATE_KEY_ASMR,
    workspace.Plots.ActivePlots.Plot1.ASMR.Placed_CHOCOLATE_KEY_ASMR:GetChildren()[19],
    "Keyboard",
    Vector3.new(-81.68230438232422, 7.859202861785889, -37.07728958129883)
)


-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Rebirth.SettingFrame
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Rebirth.SettingFrame.RebirthButton

-- Rarity Type --
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Index
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Index.SettingFrame.Scroll
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Index.SettingFrame.Scroll.IndexCard_CHOCOLATE_KEY_ASMR.RarityText

-- Auto Roll --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").PlotSystemRemotes.ConveyorButtonPress
Event:FireServer()


workspace.Plots.ActivePlots.Plot1.Conveyor
workspace.Plots.ActivePlots.Plot1.Conveyor.ActiveCrates
workspace.Plots.ActivePlots.Plot1.Conveyor.ActiveCrates.Crate_210.Attachment
workspace.Plots.ActivePlots.Plot1.Conveyor.ActiveCrates.Crate_210.Attachment.BillboardGui.Frame.RarityLabel

-- Buy Worker --
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Workers.MainWorkerFrame.PurchaseWorker
