task.spawn(function()
getgenv().autoclick = not getgenv().autoclick
while getgenv().autoclick do
task.wait()
local Event = game:GetService("ReplicatedStorage").Packages.Main.DataService.Networker._remotes.AxeService.RemoteEvent
Event:FireServer("requestChop")
end
end)


task.spawn(function()
getgenv().autochop = not getgenv().autochop
while getgenv().autochop do
task.wait()
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Main.DataService.Networker._remotes.TreeService.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Main.DataService.Networker._remotes.TreeService.RemoteEvent
Event:FireServer(
    "requestChop",
    "Tree1"
)
end

-- workspace.Map.Lobby.TreeAreas
-- workspace.Map.Lobby.TreeAreas.Area1.Tree1
end)


-- game:GetService("Players").LocalPlayer.PlayerGui.Main.Rebirth.LevelBar.Move
game:GetService("Players").LocalPlayer.PlayerGui.Main.Rebirth.Buttons.Rebirth
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Main.DataService.Networker._remotes.LevelService.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Main.DataService.Networker._remotes.LevelService.RemoteEvent
Event:FireServer(
    "requestRebirth"
)



game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Content.ScrollingFrame.AuraLuck.Buttons.Buy
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Content.ScrollingFrame
