workspace.Rooms.Room1-8

-- Auto Grab --

-- Auto Shred --
workspace.Rooms.Room1.Gameplay.Shredder
workspace.Rooms.Room1.Gameplay.Shredder.Shredder.Cube
workspace.Rooms.Room1.Gameplay.Shredder.Shredder.Cube.ProximityPrompt


-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Net["RE/Shred_Action"]
Event:FireServer(
    "Insert",
    workspace.Rooms.Room1.Gameplay.Shredder.Shredder.Cube
)

-- Auto Crank --
workspace.Rooms.Room1.Gameplay.Shredder
workspace.Rooms.Room1.Gameplay.Shredder.Shredder
workspace.Rooms.Room1.Gameplay.Shredder.Shredder.handle

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Net["RE/Shred_Action"]
Event:FireServer(
    "Crank",
    workspace.Rooms.Room1.Gameplay.Shredder.Shredder.handle
)
