-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.DataAction
Event:FireServer(
    "ClickReward",
    660.81494140625,
    74.296371459961
)

game:GetService("Players").LocalPlayer.PlayerGui.Main.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.Main.Rebirth.Main.Bar.Bar.Bar
game:GetService("Players").LocalPlayer.PlayerGui.Main.Rebirth.Main.Buttons.Rebirth


-- wins --
14.684351, 1.35249388, -2488.14941, 1, 0, 0, 0, 1, 0, 0, 0, 1

-- auto Upgrade --
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame["Double Power"].Improve.Title
game:GetService("Players").LocalPlayer.PlayerGui.Main.Upgrades.Main.ScrollingFrame["Double Power"].Buy
