-- Auto Train --
-- Equip Threadmill
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
Event:FireServer(
    buffer.fromstring("\x1AT\nGB<yY@\x96\xCD\x16Btt\xD31\xAA\xC7E@\xE62m\xB1"),
    {}
)

getgenv().AutoTrain = not getgenv().AutoTrain
while getgenv().AutoTrain do
task.wait(0.5)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
Event:FireServer(
    buffer.fromstring("\x1D"),
    {}
)
end

-- Collect Apple--
workspace.Apple
workspace.HuntSlots.HuntSlot_1.Apples -- 


-- Auto Rebirth --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
Event:FireServer(
    buffer.fromstring(" "),
    {}
)

-- Collect Cash --
-- Need Plot Target with raycast --
workspace.Village
workspace.Village.VillagePlot_5.BaseTower.SlotPad -- find SlotPad BasePart and  Find In Child AccruedGui
