---- Auto Train --
---- Equip Threadmill
---- This code was generated by Cobalt
---- https://gitlab.com/upio/cobalt

--local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
--Event:FireServer(
--	buffer.fromstring("\x1AT\nGB<yY@\x96\xCD\x16Btt\xD31\xAA\xC7E@\xE62m\xB1"),
--	{}
--)

--getgenv().AutoTrain = not getgenv().AutoTrain
--while getgenv().AutoTrain do
--	task.wait(0.5)
--	-- This code was generated by Cobalt
--	-- https://gitlab.com/upio/cobalt

--	local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
--	Event:FireServer(
--		buffer.fromstring("\x1D"),
--		{}
--	)
--end

---- Collect Apple--
--workspace.Apple
--workspace.HuntSlots.HuntSlot_1.Apples -- 


---- Auto Rebirth --
---- This code was generated by Cobalt
---- https://gitlab.com/upio/cobalt

--local Event = game:GetService("ReplicatedStorage").ZAP.ZAP_RELIABLE
--Event:FireServer(
--	buffer.fromstring(" "),
--	{}
--)

---- Collect Cash --
---- Need Plot Target with raycast --
--workspace.Village
--workspace.Village.VillagePlot_5.BaseTower.SlotPad -- find SlotPad BasePart and  Find In Child AccruedGui


local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/refs/heads/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")
local Character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()

local Enableds, Connections = {["Train"] = false, ["Cash"] = false,  ["Rebirth"] = false}, {}

local CashToggle = nil

local Packets = {
	["ZAP_RELIABLE"] = ReplicatedStorage:QueryDescendants("#ZAP > #ZAP_RELIABLE")[1]
}

local Plot = nil

Connections.CharacterAdded = LocalPlayer.CharacterAdded:Connect(function(newCharacter)
	Character = newCharacter
end)

local function GetPlot()
	local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart")
	if not rootPart then return nil end

	local rayOrigin = rootPart.Position
	local rayDirection = Vector3.new(0, -100, 0)

	local raycastParams = RaycastParams.new()
	raycastParams.FilterDescendantsInstances = {Character}
	raycastParams.FilterType = Enum.RaycastFilterType.Exclude

	local raycastResult = workspace:Raycast(rayOrigin, rayDirection, raycastParams)

	if raycastResult then
		local hit = raycastResult.Instance
		if not hit then return nil end

		local target = hit

		while target ~= workspace do
			task.wait()

			local baseTower = target:FindFirstChild("BaseTower")
			if baseTower then break end
			
			--[[
			if target and target.Name:find("Plot_") then
				local folderTarget = target.Parent
				
				if folderTarget ~= nil then
					local ancestorTarget = folderTarget.Parent 
					if ancestorTarget and ancestorTarget.Parent == workspace then
						if folderTarget.Name == "Village" then
							return target
						else
							local plotsFolder = workspace:FindFirstChild("Village")
							if plotsFolder ~= nil and folderTarget == plotsFolder then
								return target
							end
						end
					end
				end
			end
]]
			if target.Parent == workspace then break end
			
			target = target.Parent
		end
		
		return target
	end
	
	return nil
end

local function FireTouch(hitPart, targetPart)
	if firetouchinterest then
		firetouchinterest(hitPart, targetPart, 1)
		task.wait()
		firetouchinterest(hitPart, targetPart, 0)
	end
end

local function SendClick(x,y)
	VirtualInputManager:SendMouseButtonEvent(x,y,0,true,game,0)
	task.wait()
	VirtualInputManager:SendMouseButtonEvent(x,y,0,false,game,0)
end

local function FireButton(button)
	if firesignal then
		firesignal(button.Activated)
		firesignal(button.MouseButton1Click)
	end
end

local function IsFillFull(fill)
	if fill.Size.X.Scale >= 1 then
		return true
	end
	return false
end

-- Train Function (Working) --
local function HandleTrain()
	if not Enableds.Train then return end
	
	local EquipTrainBufferString,  DoubleTrainBufferString = buffer.fromstring("\x1AT\nGB<yY@\x96\xCD\x16Btt\xD31\xAA\xC7E@\xE62m\xB1"), buffer.fromstring("\x1D") 

	task.spawn(function()
		Packets.ZAP_RELIABLE:FireServer(EquipTrainBufferString,{})

		while Enableds.Train do
			Packets.ZAP_RELIABLE:FireServer(DoubleTrainBufferString,{})
			task.wait(0.5)
		end
	end)
end

-- Cash Function (WIP) --
local function HandleCash()
	if not Enableds.Cash then return end
	
	Plot = (Plot ~= nil and Plot.Parent ~= nil) and Plot or GetPlot()
	if Plot == nil then
		warn("Plot tidak di temukan")
		
		if CashToggle then
			Enableds.Cash = false
			CashToggle:Replace(false)
		end
		
		return
	end
	
	local baseTowerFolder = Plot:FindFirstChild("BaseTower")
	if not baseTowerFolder then
		warn("BaseTower tidak di temukan di ", Plot:GetFullName())
		
		Plot = nil
		
		if CashToggle then
			Enableds.Cash = false
			CashToggle:Replace(false)
		end

		return
	end
	
	for _, slotPad in pairs(baseTowerFolder:GetChildren()) do
		if slotPad:IsA("BasePart") and slotPad.Name == "SlotPad" then
			task.wait()
			
			local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart")
			if rootPart then 
				FireTouch(rootPart, slotPad)
			end
		end
	end

	--task.spawn(function()
	--	while Enableds.Rebirth do
			
	--		task.wait(5)
	--	end
	--end)
end

-- Rebirth Function (WIP) --
local function HandleRebirth()
	if not Enableds.Rebirth then return end
	
	local RebirthBufferString = buffer.fromstring(" ") 

	task.spawn(function()
		while Enableds.Rebirth do
			Packets.ZAP_RELIABLE:FireServer(RebirthBufferString,{})
			task.wait(5)
		end
	end)
end

-- Apple Function (Patched) --
local function HandleApple()
	local appleCache = {}

	for _, apple in ipairs(workspace:GetChildren()) do
		if apple ~= nil and apple.Parent ~= nil and apple:IsA("BasePart") and apple:FindFirstChildOfClass("TouchTransmitter") then
			table.insert(appleCache, apple)
		end
	end

	local huntSlotFolder = workspace:FindFirstChild("HuntSlots")
	if huntSlotFolder then
		for _, huntSlot in ipairs(huntSlotFolder:GetChildren()) do
			local applesFolder = huntSlot:FindFirstChild("Apples")
			if not applesFolder then continue end

			for _, apple in ipairs(applesFolder:GetChildren()) do
				if apple ~= nil and apple.Parent ~= nil and apple:IsA("BasePart") and apple:FindFirstChildOfClass("TouchTransmitter") then
					table.insert(appleCache, apple)
				end
			end
		end
	end

	while #appleCache > 0 do
		task.wait()

		local apple = table.remove(appleCache, 1)
		if apple ~= nil and apple.Parent ~= nil then
			local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart")
			if rootPart then
				FireTouch(Character.PrimaryPart, apple)
			end
		end
	end
end

local Window = UI:CreateWindow({
	Name = "Find the Egg for a Brainrot",
	Destroying = function()
		for key, connection in pairs(Connections) do
			if connection then
				connection:Disconnect()
			end
		end

		for key, enabled in pairs(Enableds) do
			Enableds[key] = false
		end
	end
})

Window:AddToggle({
	Text = "Auto Train",
	Value = false,
	Flag = "train_enabled",
	Callback = function(value)
		Enableds.Train = value
		HandleTrain()
	end
})

CashToggle = Window:AddToggle({
	Text = "Collect Cash",
	Value = false,
	Flag = "cash_enabled",
	Callback = function(value)
		Enableds.Cash = value
		HandleCash()
	end
})

Window:AddToggle({
	Text = "Auto Rebirth",
	Value = false,
	Flag = "rebirth_enabled",
	Callback = function(value)
		Enableds.Rebirth = value
		HandleRebirth()
	end
})

--[[
Window:AddButton({
	Text = "Collect Apple",
	MethodType = "DebounceClick",
	Callback = HandleApple
})
]]

Window:AddLabel({
	Text = "YouTube: Crokyreo",
	TextColor3 = Color3.fromRGB(255, 255, 255)
})
