game:GetService("Players").LocalPlayer.PlayerGui.UiFolder.Main.HUD.ThrowBar.CurrentMulti.Size.Y.Scale >= 1

game:GetService("Players").LocalPlayer.PlayerGui.UiFolder.Main.HUD.Coin.ThrowCoin

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Assets.Events.CoinThrow
local Event = game:GetService("ReplicatedStorage").Assets.Events.CoinThrow
Event:FireServer(
    "Copper Coin",
    Vector3.new(-1162.03125, 0.72600001096725, -176.85087585449)
)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Assets.Events.CoinLanded
local Event = game:GetService("ReplicatedStorage").Assets.Events.CoinLanded
Event:FireServer(
    2,
    Vector3.new(-1162.03125, 0.72600001096725, -176.85087585449),
    "Copper Coin",
    nil,
    nil
)


-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Assets.Events.SellAll
local Event = game:GetService("ReplicatedStorage").Assets.Events.SellAll
Event:FireServer()



-- auto upgrade / buy --
game:GetService("Players").LocalPlayer.PlayerGui.UiFolder.Main.Frames.Upgrades.SFHolder["Luck Multiplier"]

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Assets.Events.RequestUpgrade
local Event = game:GetService("ReplicatedStorage").Assets.Events.RequestUpgrade
Event:FireServer(
    "Value Multiplier"
)

-- buy --
game:GetService("Players").LocalPlayer.PlayerGui.UiFolder.Main.Frames.CoinShop.SFcontainer.SF["Aether Coin"].Main.ButtonContainer.BuyButton

game:GetService("Players").LocalPlayer.PlayerGui.UiFolder.Main.Frames.CoinShop.SFcontainer.SF["Basic Coin"].Main.ButtonContainer.BuyButton.PriceText

Equip, Equipped
