-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Libs.Remote.__comm__.RE.ResourceDropOff
Event:FireServer(
    workspace:GetChildren()[18].Unlockable.Block6.DropOffPads.DropOffPad_4.DropOffPad,
    true
)


workspace:GetChildren()[18].Unlockable
workspace:GetChildren()[18].Unlockable.Block2.DropOffPads.DropOffPad_3.DropOffPad

-- game:GetService("Players").LocalPlayer.PlayerGui.RightGui.RLFrame.CollectButton
