-- Rebirth --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.RebirthButtonEvent
Event:FireServer()

game:GetService("Players").LocalPlayer.PlayerGui.MainUI.LeftButtons.Holder.Rebirth.Notify.TextLabel.Text == "100"


-- wins farm --
workspace.StageWinPaths.Normal["1"].Hitbox
workspace.StageWinPaths.Normal

-- collect phonk --
-- need teleport and back to save cframe --
workspace.Map.SpeedTools.P9.Hitbox
workspace.Map.SpeedTools

