workspace.FarmStar.Platforms["10952058440"]

workspace.FarmStar.Platforms["10952058440"].RNG.Button.FS_RollDronesPrompt

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Net.RequestRollDrones
Event:FireServer(
    {}
)

-- upgrade drone --
workspace.FS_ClientDrones["10952058440"]["d-2"]

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Net.RequestUpgradeDrone
Event:FireServer(
    {
        droneId = "d-2"
    }
)

-- upgrade boost --

-- Upgrade Drone Luck, Drone Rolls
workspace.FarmStar.Platforms["10952058440"].Board3.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard:GetChildren()[4].FS_UpgradeBoardUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Board3.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.FS_UpgradeBoardUpgradeClick

-- Cargo, Mining Speed --
workspace.FarmStar.Platforms["10952058440"].Board2.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard:GetChildren()[4].FS_UpgradeBoardUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Board2.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.FS_UpgradeBoardUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Platform.Platform2.Board2.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard:GetChildren()[4].FS_UpgradeBoardUpgradeClick

-- Dock Platforms, Dock Storage --
workspace.FarmStar.Platforms["10952058440"].Board1.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard:GetChildren()[4].FS_UpgradeBoardUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Board1.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.FS_PlatformUpgradeClick

workspace.FarmStar.Platforms["10952058440"].Board1.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.Content.RightBlock.TitleRow.Title

-- Expand Farm --
workspace.FarmStar.Platforms["10952058440"].Board4.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.FS_PlatformUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Board4.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.Content.TitleRow.Title

-- Planet Upgrade --
workspace.FarmStar.Platforms["10952058440"].Board7.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.FS_UpgradeBoardUpgradeClick
workspace.FarmStar.Platforms["10952058440"].Board7.BoardSurface.FS_UpgradeBoardGui.UpgradeBoard.Card.Content.TextStack.TitleRow.Title



-- collect ore --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Net.RequestCollectDockOre
Event:FireServer(
    {
        dockIndex = 2
    }
)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Net.RequestCollectDockOre
Event:FireServer(
    {
        dockIndex = 3
    }
)

workspace.FarmStar.Platforms["10952058440"].Platform.Docks.DockPlatform1["1"]
workspace.FarmStar.Platforms["10952058440"].Platform.Docks.DockPlatform1
workspace.FarmStar.Platforms["10952058440"].Platform.Docks.DockPlatform2
workspace.FarmStar.Platforms["10952058440"].Platform.Docks.DockPlatform3
workspace.FarmStar.Platforms["10952058440"].Platform.Platform5
workspace.FarmStar.Platforms["10952058440"].Platform.Platform5.Docks.DockPlatform1["1"]
