game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.Rebirth.Frame.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.Rebirth.Frame.Progress.Bar
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.Rebirth
Event:FireServer()


workspace.Eggs
workspace.Eggs.Hacked

-- buy trail--
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.TrailShop.ScrollingFrame:GetChildren()[12].Visible == true 
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.TrailShop.ScrollingFrame:GetChildren()[4].Buttons.CashButton
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.TrailShop.ScrollingFrame:GetChildren()[6].Buttons.CashButton.TextLabel.Text == "$"

-- upgrade Brainrots --
workspace.Bases.Base1.Slots
workspace.Bases.Base1.Slots.Slot1 -- SlotState == Empty
workspace.Bases.Base1.Slots.Slot2.UpgradeModel.UpgradePart.SurfaceGui.ImageButton


-- claim index --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.ClaimIndexRewards
Event:FireServer()

-- upgrade treadmill --
workspace.Treadmills.Base1 -- OwnerId number 
workspace.Treadmills.Base1.UpgradeFrame.SurfaceGui.CanvasGroup.Buy
