Game Name: +1 Fat Per Click
-- auto click --
use Maswa Clicker


-- auto rebirth --
 game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.RebirthFrame.RebirthBackground.RebirthButton

game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.RebirthFrame.RebirthBackground.Bar.BarCanvas.Progress

-- auto upgrade 

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").BuyBoost
Event:FireServer(
    "Damage"
)


-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").BuyBoost
Event:FireServer(
    "Wins"
)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt
local Event = game:GetService("ReplicatedStorage").BuyBoost
Event:FireServer(
    "Luck"
)
