game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.BallRow.Slots
game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.BallRow.Slots.Ball_B14.Inner.NumberLabel
game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.BallRow.Slots.Ball_B4

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").BingoRemotes.NumberCalled
firesignal(Event.OnClientEvent, 
    {
        letter = "I",
        index = 4,
        number = 26
    }
)

game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.CardArea.Row1.Slot1.Card1.GridArea.Grid
game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.CardArea.Row1.Slot1.Card1.GridArea.Grid.C1_1
game:GetService("Players").LocalPlayer.PlayerGui.BingoGui.CardArea.Row1.Slot1.Card1.GridArea.Grid.C1_1.Number
