if true then warn("+1 Speed Per Click is WIP") return end

-- 0 0.839216 1 0.345098 0 0.0675 0.839216 1 0.345098 0 1 0.27451 1 0.305882 0 

-- Fast Click --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Network.RemoteEventStorage.ClickEnergy
Event:FireServer()

-- Fast Cash --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Network.RemoteEventStorage.ThrowStarted
Event:FireServer(
    100990612.19127,
    6933723.119628
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Network.RemoteEventStorage.RefreshPlayerMovement
Event:FireServer()

-- instant
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Network.RemoteEventStorage.ThrowReward
Event:FireServer(
   9999
)

-- Fast Throw Click --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Network.RemoteEventStorage.ThrowBoostClick
Event:FireServer()

-- Auto Rebirth --
