
-- Upgrade --

-- TNT Radius --
local Event = game:GetService("ReplicatedStorage")["ReplicatedStorage.Shared.Modules.SaveData_27_RemoteFunction"]
Event:InvokeServer(
    {
        rankIndex = 9,
        itemKind = "tntRadius"
    }
)

-- Gunpowder Storage --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage")["ReplicatedStorage.Shared.Modules.SaveData_27_RemoteFunction"]
Event:InvokeServer(
    {
        rankIndex = 5,
        itemKind = "gunpowderStorage"
    }
)

-- Active TNT --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage")["ReplicatedStorage.Shared.Modules.SaveData_27_RemoteFunction"]
Event:InvokeServer(
    {
        rankIndex = 8,
        itemKind = "activeGunpowder"
    }
)

-- WalkSpeed --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage")["ReplicatedStorage.Shared.Modules.SaveData_27_RemoteFunction"]
Event:InvokeServer(
    {
        rankIndex = 2,
        itemKind = "walkSpeed"
    }
)
