-- Bucket Used --
game:GetService("ReplicatedStorage").VerdantRemotes["VDT_Bucket.Used"]:FireServer()
end
game:GetService("Players").LocalPlayer.PlayerGui.Interface.Holder.BucketFill.Bar.Scale


-- Drain Machine --
game:GetService("ReplicatedStorage").VerdantRemotes["VDT_Bucket.Poured"]:FireServer(
    workspace.Scripted.CheckpointParts["1"]:GetChildren()[3].Scripted.ProximityPosition.ProximityPrompt
)

-- Take Token --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.VerdantRemotes.VDT_Tokens.Take
local Event = game:GetService("ReplicatedStorage").VerdantRemotes["VDT_Tokens.Take"]
Event:FireServer(
    workspace.Scripted.CheckpointParts["1"]:GetChildren()[3].Scripted.ProximityPosition.ProximityPrompt
)
