-- auto roll --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.RemoteEvents.BossRoomRollSummonPool
Event:FireServer()

workspace.BLDS.BossRoom4 -- Attribute OwnerId

workspace.BLDS.BossRoom4.SummonAltar.SummonAltarClientRuntime.BoneGrunt
workspace.BLDS.BossRoom4.SummonAltar.SummonAltarClientRuntime.SummonOfferSlot1Anchor.SummonOfferInfo.Rarity
workspace.BLDS.BossRoom4.SummonAltar.SummonAltarClientRuntime.SummonOfferSlot1Anchor.SummonOfferInfo.NameLabel.Text is Rolling
workspace.BLDS.BossRoom4.SummonAltar.SummonAltarClientRuntime.SummonOfferSlot1Anchor.SummonOfferSlot1.BuySummonOfferPrompt
workspace.BLDS.BossRoom4.SummonAltar.SummonAltarClientRuntime.SummonOfferSlot1Anchor.SummonOfferInfo.Mutation



game:GetService("Players").LocalPlayer.PlayerGui.AutoRollGui.Root.List.PauseOnRaritySettings.RarityOptions
game:GetService("Players").LocalPlayer.PlayerGui.AutoRollGui.Root.List.PauseOnRaritySettings.RarityOptions.Rarity_Epic



