-- Redeem Code --
FREEBOOST, BONUS500, WELCOME1
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RedeemPromoCode
Event:FireServer(
    "FREEBOOST"
)

-- Auto Rebirth --
local Event = game:GetService("ReplicatedStorage").Events.RequestRebirth
Event:InvokeServer()
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Rebirth.Bar.Progress
game:GetService("Players").LocalPlayer.PlayerGui.GUI.Frames.Rebirth.RebirthButton

-- Click Train --
local Event = game:GetService("ReplicatedStorage").Events.TrainerBubble
Event:FireServer(
    79
)
game:GetService("Players").LocalPlayer.PlayerGui.GUI.TrainBubbles
game:GetService("Players").LocalPlayer.PlayerGui.GUI.TrainBubbles.Bubble200

-- Auto Wins --
workspace.Map.GiveWins.OneWin
workspace.Map.GiveWins.OneWin.Button15

-- Claim Playtime --
-- 1-6
local Event = game:GetService("ReplicatedStorage").Events.PlaytimeClaim
Event:FireServer(
    6
)
