local Enableds, Connections, Packets = {}, {}, {}

local RebirthFrame, RebirthFill, RebirthButton = nil, nil, nil

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = 
Event:FireServer()



-- Finish Race
workspace.RaceInfo.Win

local function IsFillFull(fill)
	return fill.Size.X.Scale >= 1
end

local function HandleClick()
   if not Enableds.Click then return end
   Packets.Click = Packets.Click or ReplicatedStorage.Remotes.JumpXpEvent
   task.spawn(function()
       while Enableds.Click do
          Packets.Click:FireServer()
          task.wait()
       end
   end)
end

local function FireRebirth()
	if IsFillFull(RebirthFill) and Enableds.Rebirth then
		FireButton(RebirthButton)
	end
end

local function HandleRebirth()
	if Connections.Rebirth then Connections.Rebirth:Disconnect() Connections.Rebirth = nil end
	if not Enableds.Rebirth then return end
	RebirthFrame = RebirthFrame or PlayerGui:QueryDescendants("#MainUI > #Frames > #Rebirth > #Main > #Holder")[1]
	if RebirthFrame then
		RebirthFill = RebirthFill or RebirthFrame:QueryDescendants("#RequirementsFrame > #Main > #Main > #Progress")[1]
		RebirthButton = RebirthButton or RebirthFrame:QueryDescendants("#Frame > #Rebirth")[1]
	end
	Connections.Rebirth = RebirthFill:GetPropertyChangedSignal("Size"):Connect(FireRebirth)
	task.spawn(function()
		while Enableds.Rebirth do
			FireRebirth()
			task.wait(1)
		end
	end)
end

local function HandleFinishRace()
	local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart")
	if not rootPart then return end -- Batalkan jika karakter tidak ada

	local rayOrigin = rootPart.Position
	local rayDirection = Vector3.new(0, -100, 0)

	local raycastParams = RaycastParams.new()
	raycastParams.FilterDescendantsInstances = {Character}
	raycastParams.FilterType = Enum.RaycastFilterType.Exclude

	local raycastResult = workspace:Raycast(rayOrigin, rayDirection, raycastParams)

	if raycastResult then
		local hit = raycastResult.Instance
		if not hit then return end

		local target = hit

		while target ~= workspace do
			task.wait()

      for _, child in ipairs(target:GetChildren()) do
         if child and child:IsA("BasePart") and child.Name:find("Win") then
            target = child
            break
         end
      end

			if target and target.Name:find("Win")  then
				break
			end

			target = target.Parent
		end

		if not (target and target.Name:find("Win")) then
			return
		end
		
		while LocalPlayer.GameplayPaused do
			task.wait(0.1)
		end
		
		if target then
			local newCFrame = target.CFrame
			PlayerRequestStreamAroundAsync(newCFrame.Position, 5)
			Character:MoveTo(newCFrame.Position)
		end
	end
end
