-- Click X2 Grass --
game:GetService("Players").LocalPlayer.PlayerGui.GameGui.R22_Grass2xPrompt

-- Auto Sell --
workspace.ServerServiceZones.Map_1.BackpackFullActionsSellTarget
workspace.PlayerPets.Baby_penguin856.SellZone1.Attachment.R22GrassSellPrompt
-- inventory
game:GetService("Players").LocalPlayer.PlayerGui.GameGui.MainUI.Left_GUI.Value_GUI.Bakcpack.TextValue.Text == "/"

-- Click Buff --
game:GetService("Players").LocalPlayer.PlayerGui.GameGui.R22_TimedBuffPrompt.Visible == true

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").R22.Remotes.TimedBuffAction
Event:FireServer(
    "Click"
)
