workspace.NewPlots.Plot3.Merge

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").GumballRemotes.CollectClientGumball
Event:FireServer(
    "3abdbe98-c5b3-4602-9c68-9411c97f5bfc"
)


-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").GumballRemotes.SpawnClientGumball
firesignal(Event.OnClientEvent, 
    "1e4e12b4-9ba1-4cce-aae3-f02af929f127",
    "Red",
    CFrame.new(-544.61706542969, 31.311117172241, -316.39593505859, 0.17960619926453, 0, 0.98373860120773, 0, 1, 0, -0.98373860120773, 0, 0.17960619926453),
    1,
    "Red",
    "Gumball"
)


workspace.NewPlots.Plot3.Process

workspace.NewPlots.Plot3.ProcessComplete



Buy
workspace.NewPlots.Plot3.Buy1
workspace.NewPlots.Plot3.Buy100
workspace.NewPlots.Plot3.Buy25
workspace.NewPlots.Plot3.Buy5


workspace.NewPlots.Plot3.ProcessUpgrade
