
for _,v in ipairs(workspace.ItemSpawns.StartArea.Spawn1.Items:GetChildren()) do
task.wait(0.1)
-- Cached Event Path: ReplicatedStorage.EVENTS.PlayerEvents.CollectItem
local Event = game:GetService("ReplicatedStorage").EVENTS.PlayerEvents.CollectItem
Event:FireServer(
    v
)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.EVENTS.PlayerEvents.ThrowItem
local Event = game:GetService("ReplicatedStorage").EVENTS.PlayerEvents.ThrowItem
Event:FireServer(
    Vector3.new(0.96049702167511, -0.25137504935265, -0.11939886957407),
    10
)
end





