local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/refs/heads/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer.PlayerGui

local CleanEnabled = false

local GrindingMachinePosition = Vector3.new(122, 18, 135)

local TrashFillConnection, EnergyFillConnection, DebrisAddedConnection, DebrisRemovedConnection, GameCleanConnection = nil, nil, nil, nil, nil
local TrashDebounce, EnergyDebounce = false, false
local FoodList = {"SodaCan", "EnergyBar"}

local function FireButton(button)
	if firesignal then
		firesignal(button.Activated)
		firesignal(button.MouseButton1Click)
	end
end


local function IsCursorPerfect(cursor)
	local currentY=cursor.Position.X.Scale
	if currentY>=0.45 and currentY<=0.48 then
		return true
	end
	return false
end

local Window = UI:CreateWindow({
	Name = "Clean the Backyard",
	Destroying = function()
		CleanEnabled = false
		TrashDebounce, EnergyDebounce = false, false
		if GameCleanConnection then GameCleanConnection:Disconnect() GameCleanConnection = nil end
		if TrashFillConnection then TrashFillConnection:Disconnect() TrashFillConnection = nil end
		if EnergyFillConnection then EnergyFillConnection:Disconnect() EnergyFillConnection = nil end
		if DebrisRemovedConnection then DebrisRemovedConnection:Disconnect() DebrisRemovedConnection = nil end
		if DebrisAddedConnection then DebrisAddedConnection:Disconnect() DebrisAddedConnection = nil end
	end
})

--[[




-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.EVENTS.PlayerEvents.BuyRechargeItem
local Event = game:GetService("ReplicatedStorage").EVENTS.PlayerEvents.BuyRechargeItem
Event:FireServer()


-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.EVENTS.PlayerEvents.BuyEnergyBarItem
local Event = game:GetService("ReplicatedStorage").EVENTS.PlayerEvents.BuyEnergyBarItem
Event:FireServer()

workspace.ItemSpawns
workspace.ItemSpawns.Area1
workspace.ItemSpawns.StartArea
workspace.ItemSpawns.StartArea.Spawn1.Items

122, 18, 135
]]

--[[


Window:AddLabel("Position Type")

local PositionSelector = Window:AddSelector({
	Options = {"None", "VendingMachine", "GrindingMachine"},
	Value = "None",
	Callback = function(value)
		PositionButton.Visible = value ~= "None"
		PositionType = value
	end
})

PositionButton = Window:AddButton({
	Text = "Set Position",
	Visible = false,
	Callback = function()
		local character = LocalPlayer.Character
		if character and character.Parent then
			if PositionType == "VendingMachine" then
				VendingMachinePosition = character.PrimaryPart.Position
			elseif PositionType == "GrindingMachine" then
				GrindingMachinePosition = character.PrimaryPart.Position
			end
		end

		if VendingMachinePosition ~= nil and GrindingMachinePosition ~= nil and VendingMachinePosition ~= GrindingMachinePosition and VendingMachinePosition ~= Vector3.zero and GrindingMachinePosition ~= Vector3.zero then
			PositionSelector:Set("None")
		end
	end
})

local SpawnsItems = nil

Window:AddSelect({
	Text = "Clean Target",
	Callback = function(target)
		SpawnsItems = FindMatchAncestor(target, workspace, function(instance)
			if instance and instance.Name:find("Items") then
				return true
			end

			return false
		end)
	end
})
]]

-- local CleanToggle = nil

-- CleanToggle = 

local function PlayClean(item, character, energyFill, trashFill)
	task.wait()

	if not CleanEnabled then return end
	if not (item ~= nil and item.Parent ~= nil) then return end

	if energyFill.Size.Y.Scale <= 0.25 then
		repeat task.wait(1) until not EnergyDebounce or not CleanEnabled or not (item ~= nil and item.Parent ~= nil)
	end

	if not CleanEnabled then return end
	if not (item ~= nil and item.Parent ~= nil) then return end

	local itemPart = item:FindFirstChildWhichIsA("BasePart")
	if itemPart then
		character:MoveTo(Vector3.new(itemPart.Position.X, character.PrimaryPart.Position.Y, itemPart.Position.Z))
		task.wait(0.5)
	end

	if not CleanEnabled then return end
	if not (item ~= nil and item.Parent ~= nil) then return end

	ReplicatedStorage.EVENTS.PlayerEvents.CollectItem:FireServer(item)
	task.wait(0.5)

	if not CleanEnabled then return end
	if not (item ~= nil and item.Parent ~= nil) then return end

	if trashFill.Size.Y.Scale >= 1 then
		repeat task.wait(1) until not TrashDebounce or not CleanEnabled or not (item ~= nil and item.Parent ~= nil)
	end
end

Window:AddToggle({
	Text = "Auto Clean",
	Value = false,
	Flag = "clean_enabled",
	Callback = function(value)
		CleanEnabled = value

		if TrashFillConnection then TrashFillConnection:Disconnect() TrashFillConnection = nil end
		if EnergyFillConnection then EnergyFillConnection:Disconnect() EnergyFillConnection = nil end
		if DebrisRemovedConnection then DebrisRemovedConnection:Disconnect() DebrisRemovedConnection = nil end
		if DebrisAddedConnection then DebrisAddedConnection:Disconnect() DebrisAddedConnection = nil end
		
		if value then
			local energyFill = PlayerGui.InterfaceUI.StatsUI.Energy.ProgressBar.BarFrame
			local trashFill = PlayerGui.InterfaceUI.StatsUI["Garbage Bag"].ProgressBar.BarFrame

			local character = LocalPlayer.Character
			local saveCFrame = character.PrimaryPart.CFrame
			local spawnedDebris = workspace:FindFirstChild("SpawnedDebris")

			local food = nil

			TrashDebounce, EnergyDebounce = false, false

			DebrisAddedConnection = spawnedDebris.ChildAdded:Connect(function(child)
				if child.Name == "SodaCan" or child.Name == "EnergyBar" then
					food = child
				end
			end)
			
			DebrisRemovedConnection = spawnedDebris.ChildRemoved:Connect(function(child)
				if child.Name == "SodaCan" or child.Name == "EnergyBar" and food == child then
					food = nil
				end
			end)

			food = (food ~= nil and food.Parent) and food or (spawnedDebris:FindFirstChild("SodaCan") or spawnedDebris:FindFirstChild("EnergyBar"))

			TrashFillConnection = trashFill:GetPropertyChangedSignal("Size"):Connect(function()
				if trashFill.Size.Y.Scale >= 1 and not TrashDebounce then
					TrashDebounce = true
					character:MoveTo(Vector3.new(GrindingMachinePosition.X, character.PrimaryPart.Position.Y, GrindingMachinePosition.Z))
					task.wait(1)
					ReplicatedStorage.EVENTS.PlayerEvents.ThrowItem:FireServer(Vector3.new(0.96049702167511,-0.25137504935265,-0.11939886957407),10)
					task.wait(0.1)
					TrashDebounce = false
				end
			end)

			EnergyFillConnection = energyFill:GetPropertyChangedSignal("Size"):Connect(function()
				if energyFill.Size.Y.Scale <= 0.25 and not EnergyDebounce then
					EnergyDebounce = true

					food = (food ~= nil and food.Parent) and food or (spawnedDebris:FindFirstChild("SodaCan") or spawnedDebris:FindFirstChild("EnergyBar"))
					if not food then
						local randomfoodIndex = math.random(1, #FoodList)
						local randomFoodName = FoodList[randomfoodIndex]

						if not randomFoodName or randomFoodName == "SodaCan" then
							ReplicatedStorage.EVENTS.PlayerEvents.BuyEnergyBarItem:FireServer()
						elseif randomFoodName == "EnergyBar" then
							ReplicatedStorage.EVENTS.PlayerEvents.BuyRechargeItem:FireServer()
						end
		
						task.wait()

						if not (food and food.Parent) then
							repeat
								task.wait()
								food = (food ~= nil and food.Parent) and food or (spawnedDebris:FindFirstChild("SodaCan") or spawnedDebris:FindFirstChild("EnergyBar"))
							until (food ~= nil and food.Parent ~= nil)
						end
					end

					if food and energyFill.Size.Y.Scale <= 0.25 then
						local foodPart = food:FindFirstChildWhichIsA("BasePart")
						if foodPart then
							character:MoveTo(Vector3.new(foodPart.Position.X, character.PrimaryPart.Position.Y, foodPart.Position.Z))
							task.wait(1)
						end

						ReplicatedStorage.EVENTS.PlayerEvents.CollectItem:FireServer(food)
						task.wait(1)

						ReplicatedStorage.EVENTS.PlayerEvents.ConsumeItem:FireServer(false, food.Name)
						task.wait(1)
					end

					task.wait(0.1)
					EnergyDebounce = false
				end
			end)

			task.spawn(function()
				while CleanEnabled do
					task.wait()
					
					local itemSpawns = workspace:FindFirstChild("ItemSpawns")
					local itemCache = {}
					
					for _, itemAll in ipairs(itemSpawns:GetDescendants()) do
						if itemAll.Name:lower():find("game") and (itemAll:IsA("SpotLight") or itemAll:IsA("PointLight") or itemAll:IsA("SurfaceLight")) and not table.find(itemCache, itemAll.Parent) then
							table.insert(itemCache, itemAll.Parent)
						end
					end
					
					for _, area in ipairs(itemSpawns:GetChildren()) do
						task.wait()
						if not CleanEnabled then break end
						if not (area ~= nil and area.Parent ~= nil) then continue end
						
						for _, spwn in ipairs(area:GetChildren()) do
							task.wait()
							if not CleanEnabled then break end
							if not (spwn ~= nil and spwn.Parent ~= nil) then continue end
							
							local items = spwn:FindFirstChild("Items")
							if items then
								local itemChildren = items:GetChildren()
								if #itemChildren <= 0 then continue end
								
								for _, item in ipairs(itemChildren) do
									if not table.find(itemCache, item) then
										table.insert(itemCache, item)
									end
								end
							end
						end
					end
					
					for _, item in ipairs(itemCache) do
						task.wait()
						PlayClean(item, character, energyFill, trashFill)
					end
					
					table.clear(itemCache)
				end
			end)
		end
	end
})


Window:AddToggle({
	Text = "Auto Game Clean",
	Callback = function(value)
		if GameCleanConnection then GameCleanConnection:Disconnect() GameCleanConnection = nil end

		if value then
			local clickButton = PlayerGui.GameCleanUI.MainFrame.ClickButton
			local cursor = PlayerGui.GameCleanUI.MainFrame.LineFrame.MovingLine
			local boxFrame = PlayerGui.GameCleanUI.MainFrame.LineFrame.BoxFrame

			GameCleanConnection = cursor:GetPropertyChangedSignal("Position"):Connect(function()
				if IsCursorPerfect(cursor)  then
					FireButton(clickButton)
				end
			end)

			if IsCursorPerfect(cursor)  then
				FireButton(clickButton)
			end
		end
	end
})

Window:AddLabel("YouTube: Crokyreo")
