workspace.Plots.Plot2 -- OwnerUserId

-- Complete Tycoon --
 workspace.Plots.Plot2.Buttons.GarageSetup.Button workspace.Plots.Plot2.Buttons.SpinnyChair.Button 

-- Phone Offer --
game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.PhoneFrame.Visible == true 

game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.PhoneFrame.Frame.MainFrame.OptionsFrame.Option.LayoutOrder == 1

-- Upgrade Income --
game:GetService("Players").LocalPlayer.PlayerGui.StandBillboard
game:GetService("Players").LocalPlayer.PlayerGui:GetChildren()[31].StandFrame.UpgradeButton

-- Auto Hack --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.Game.HackableTap
Event:FireServer()

game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.HackFrame.Visible
game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.HackFrame.HackButton
