game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.Rebirth.Main.Holder.Frame.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.MainUI.Frames.Rebirth.Main.Holder.RequirementsFrame.ProgressCanvas.Main.Progress



-- Win HitBox --
workspace.Generated.Progression.WinBoxes.WinBoxNormal_Stage03.Hitbox
workspace.Generated.Progression.WinBoxes


-- Checkpoint --
workspace.Generated.Zones
workspace.Generated.Zones.Zone_04.ZoneHitbox_04 -- Different as Wins


-- Toggle Level Up
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RuntimeRemoteEvents.LongEarningIntentEvent
Event:FireServer(
    true
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RuntimeRemoteEvents.LongEarningIntentEvent
Event:FireServer(
    false
)

-- Equip Best --
workspace.Generated.Progression.HomeBase.StretchPads
workspace.Generated.Progression.HomeBase.StretchPads.Stretch1.Hitbox
game:GetService("Players").LocalPlayer -- EquippedStretchPad string 
