-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.ModuleScripts.Manager_关卡.Event
local Event = game:GetService("ReplicatedStorage").ModuleScripts["Manager_\229\133\179\229\141\161"].Event
Event:FireServer(
    {
        "GetBoxAndBrainrot",
        game:GetService("Players").LocalPlayer,
        10000000000000000
    }
)

-- Nexus = 10000000000000000
-- Astral = 100000000000000
-- Quantum = 1000000000000
-- OG = 100000000000
-- StarTech = 99999000000
-- Exclusive = 9990000000
-- Forbidden = 1000000000
-- Secret = 100000000
-- Void = 10000000
-- Devine = 1000000
-- God = 100000
-- Mythic = 10000
-- Legendary = 1000
-- Epic = 100
-- Rare = 50
-- Uncommon= 1
-- Common = 0.025



-- Collecth Cash --
Plot in LocalPlayer:GetAttribute("OwnTerritory")
workspace["\229\156\176\229\155\190"].Plot6.PlotModel.PlaceIUnitModel.Place_2.PlaceBrainrotModel.CollectGoldTouch

-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.RebirthGui.Frame.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.RebirthGui.Frame.ProgressBar.Bar

