-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local children = workspace.HaystackClient:GetChildren()
local part = children[math.random(1,#children)]

local Event = game:GetService("ReplicatedStorage").NeedleHaystack.PickHay
Event:FireServer(
    part:GetAttribute("HayId"),
    {}
)

-- Auto Sell --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").NeedleHaystack.SellHay
Event:FireServer()

