-- auto escape --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Shared.Remotes.BotReachedExit
Event:FireServer(
    1,
    1,
    "normal"
)

-- upgrade --
local Event = game:GetService("ReplicatedStorage").Shared.Remotes.BuyUpgrade
Event:FireServer(
    "bot", "
)

local Event = game:GetService("ReplicatedStorage").Shared.Remotes.BuyUpgrade
Event:FireServer(
    "speed"
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Shared.Remotes.BuyUpgrade
Event:FireServer(
    "crate"
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Shared.Remotes.BuyUpgrade
Event:FireServer(
    "extragen"
)


