-- Collect Cash --
workspace.Map.Plots
workspace.Map.Plots.Plot_10754301213 -- OwnerUserId
workspace.Map.Plots.Plot_10754301213.PlacedItems
workspace.Map.Plots.Plot_10754301213.PlacedItems["Wooden Table"].CashCollectHitbox
workspace.Map.Plots.Plot_10754301213.PlacedItems["Wooden Chair"].CashCollectHitbox

local Event = game:GetService("ReplicatedStorage").Events.RequestCustomerCashCollect
Event:FireServer(
    workspace.Map.Plots.Plot_10754301213.PlacedItems["Wooden Chair"]
)

-- Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.GameUI.Frames.Rebirth.Container
game:GetService("Players").LocalPlayer.PlayerGui.GameUI.Frames.Rebirth.Container.Progress.Fill
game:GetService("Players").LocalPlayer.PlayerGui.GameUI.Frames.Rebirth.Container.Buttons.Rebirth

game:GetService("ReplicatedStorage").DataModules.CodesConfig --.Codes
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

-- Redeem Code --
local Event = game:GetService("ReplicatedStorage").Events.RequestRedeemCode

Event:InvokeServer(
    "RELEASE"
)

-- Upgrade --
-- Buy Slot --
workspace.Map.Plots.Plot_10754301213.UpgradeBoard.Part.SurfaceGui.BuySlot.Essential.Stats.BuyButton

-- Roll Luck --
workspace.Map.Plots.Plot_10754301213.UpgradeBoard.Part.SurfaceGui.LuckUpgrade.Essential.Stats.BuyButton

-- Security --
workspace.Map.Plots.Plot_10754301213.Boards.UpgradeSecurity.Display.SurfaceGui.SecurityUpgrade.Essential.BuyButton

-- Upgrade Convenyor --
workspace.Map.Plots.Plot_10754301213.RollArea.UpgradeConveyor.Button
