game:GetService("Players").LocalPlayer.PlayerGui.Screen.Frames.Rebirth
game:GetService("Players").LocalPlayer.PlayerGui.Screen.Frames.Rebirth.Container.Main.Rebirth


-- upgrade --
game:GetService("Players").LocalPlayer.PlayerGui.Screen.Frames.Upgrades.Container.Main.UpgradeList

game:GetService("Players").LocalPlayer.PlayerGui.Screen.Frames.Upgrades.Container.Main.UpgradeList.Speed

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage")["ffrostflame_bridgenet2@1.0.0"].dataRemoteEvent
Event:FireServer(
    {
        {
            Action = "Buy",
            Id = "Speed"
        },
        "\x13"
    }
)


-- SurfaceGui.ImageButton.TextLabel
game:GetService("Players").LocalPlayer.PlayerGui.SoapSignLuck.Buy.Price.Text == "$"


