Game Name: Crunch My Butter

workspace.Map.Plots.Plot_10952058440.Items["1"].Objects.Keycap
workspace.Map.Plots.Plot_10952058440.Items["2"].Objects.Keycap

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.PaintInput
Event:FireServer(
    {
        workspace.Map.Plots.Plot_10952058440.Items["1"].Objects:GetChildren()[3],
        workspace.Map.Plots.Plot_10952058440.Items["1"].Objects:GetChildren()[2],
        workspace.Map.Plots.Plot_10952058440.Items["1"].Objects:GetChildren()[4],
        workspace.Map.Plots.Plot_10952058440.Items["1"].Objects:GetChildren()[6]
    }
)




-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "WalkSpeed"
)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "PaintTank"
)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "RollerSize"
)









-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "WorkerSpeed"
)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyWorker
Event:InvokeServer()


-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.WorkerCollect
Event:FireServer(
    {
        workspace.Map.Plots.Plot_10952058440.Items["1"].Objects:GetChildren()[9]
    },
    "4ebff202-70ef-4e28-9e83-4a0e5cf3b61a"
)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "RollLuck"
)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RequestBuyUpgrade
Event:InvokeServer(
    "RollSpeed"
)
