getgenv().TapActive = not getgenv().TapActive
while getgenv().TapActive do
task.wait()

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages._Index.sleitnick_knit@1.7.0.knit.Services.KickService.RF.AddKick
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.KickService.RF.AddKick
Event:InvokeServer(
    nil
)

end

game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.RebirthFrame.RebirthBackground.Bar.BarCanvas.Progress

game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.RebirthFrame.RebirthBackground.RebirthButton



-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages._Index.sleitnick_knit@1.7.0.knit.Services.BoostService.RF.PurchaseBoost
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.BoostService.RF.PurchaseBoost
Event:InvokeServer(
    "Hack"
)

game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.BoostsFrame.BoostsBackground.BoostsInnerFrame

game:GetService("Players").LocalPlayer.PlayerGui.NewGui.MainFrames.BoostsFrame.BoostsBackground.BoostsInnerFrame.DamageFrame.CashButton
