-- Untuk menepatkan Brick
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.PlaceBrickRequest
Event:FireServer(
    "Layer1_Wall4_Row1_Brick3" -- Dapatkan dari sini: workspace.TestBuilding
)
-- ini harus Row harus Urutan mulai kecil sampai besar
-- ini harus Layer harus Urutan mulai kecil sampai besar
-- ini harus Brick harus Urutan mulai kecil sampai besar

-- workspace.TestBuilding
-- workspace.TestBuilding.Layer1.Wall4_Row4_Brick3 --> Example: Layer1_Wall4_Row4_Brick3
-- workspace.TestBuilding.Layer5.Wall4_Row5_Brick14
-- workspace.TestBuilding.Layer1.Wall8_Row1_Brick1

-- Mengambil Brick --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.BrickPileRequest
Event:FireServer(
    "Brick"
)
