task.spawn(function()
getgenv().click = not getgenv().click
while getgenv().click do
task.wait()
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["acecateer_knit@1.7.2"].knit.Services.StrengthService.RE.ClickRequested
Event:FireServer()
end
end)
--[[
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["acecateer_knit@1.7.2"].knit.Services.DataService.RF.SellAllBackpackLoot
Event:InvokeServer()


game:GetService("Players").LocalPlayer.PlayerGui.RebirthGUI.Rebirth.Background
game:GetService("Players").LocalPlayer.PlayerGui.RebirthGUI.Rebirth.Background.RebirthButton
game:GetService("Players").LocalPlayer.PlayerGui.RebirthGUI.Rebirth.Background.Midleground.Bar.BarFill.Position.Scale.X >= 1

game:GetService("Players").LocalPlayer.PlayerGui.UpgradesGUI.Upgrades.Background.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.UpgradesGUI.Upgrades.Background.ScrollingFrame.UpgradeAttackSpeed.Content.BuyButton
game:GetService("Players").LocalPlayer.PlayerGui.UpgradesGUI.Upgrades.Background.ScrollingFrame.UpgradeAttackSpeed.Content.Name.Text
]]
