local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage
local RunService = Services.RunService

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")

local function GetPlot()
    local plots = workspace:FindFirstChild("Plots")
    if not plots then return nil end
    
end

workspace.Plots.KopiPahitGamerPlot.Objects["Flower Bed"]
workspace.Plots.KopiPahitGamerPlot.Objects:GetChildren()[3]._SlotVisuals.Slot_2
workspace.Plots.KopiPahitGamerPlot.Objects:GetChildren()[3].Slot2.SlotPromptAtt_2.SlotPrompt_2.ActionText --Harvest, 

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.GrowingService.RF.Harvest
Event:InvokeServer(
    workspace.Plots.KopiPahitGamerPlot.Objects:GetChildren()[3],
    2
)

-- auto stock --
workspace.Plots.KopiPahitGamerPlot.Objects["Flower Display"]

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.FlowerDisplayService.RF.StockFlower
Event:InvokeServer(
    workspace.Plots.KopiPahitGamerPlot.Objects["Flower Display"]
)

-- auto plant --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.GrowingService.RF.PlantSeed
Event:InvokeServer(
    workspace.Plots.KopiPahitGamerPlot.Objects:GetChildren()[3],
    "Rose Seed",
    4
)

-- get seed info 
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MainMenu.Main.SeedsContent.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MainMenu.Main.SeedsContent.ScrollingFrame["Tulip Seed"].SeedName
