local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage
local RunService = Services.RunService

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")

local Enableds, Connections, Packets = {["Restock"] = false, ["Harvest"] = false}, {}, {}

local function GetPlot()
    local plots = workspace:FindFirstChild("Plots")
    if not plots then return nil end

    for _, plot in ipairs(plots:GetChildren()) do
        if plot.Name == LocalPlayer.Name then
            return plot
        end
    end

    return nil
end

local Plot = GetPlot()
local ObjectsFolder = nil
if Plot then
    ObjectsFolder = Plot:FindFirstChild("Objects")
end

local function GetIndexByChildren(parent, name)
    local list = {}
    for _, child in ipairs(parent:GetChildren()) do
        if string.match(child.Name, "^"..name.."%d+$") then
            table.insert(list, {
                ["Instance"] = child,
                ["Tier"] = child.Name:match("%d+") or 0
            })
        end
    end
    return list
end

local function HandleRestock()
    if not Enableds.Restock then return end
    task.spawn(function()
        Packets.StockFlower = Packets.StockFlower or Packages._Index["sleitnick_knit@1.7.0"].knit.Services.FlowerDisplayService.RF.StockFlower
        while Enableds.Restock then
            for _, display in ObjectsFolder:GetChildren() do
                if display.Name == "Flower Display" then
                    Packets.StockFlower:InvokeServer(display)
                end
                task.wait(0.1)
            end
            task.wait(1)
        end
    end)
end

local function HandleHarvest()
    if not Enableds.Harvest then return end
    task.spawn(function()
        Packets.Harvest = Packets.Harvest or Packages._Index["sleitnick_knit@1.7.0"].knit.Services.GrowingService.RF.Harvest
        while Enableds.Harvest then
            for _, bed in ObjectsFolder:GetChildren() do
                if bed.Name == "Flower Bed" then
                    local slots = GetIndexByChildren(bed, "Plot")
                    for _, slot in ipairs(slots) do
                       local tier = tostring(slot.Tier)
                       if tier ~= "0" then
                          local prompt = slot.Instance:QueryDescendants("#SlotPromptAtt_"..tier.." > #SlotPrompt_"..tier)[1]
                          if prompt and prompt.ActionText == "Harvest" then
                             Packets.Harvest:InvokeServer(bed,tier)
                          end
                       end
                       task.wait(0.1)
                    end
                end
                task.wait(0.1)
            end
            task.wait(1)
        end
    end)
end

local Window = UI:CreateWindow({
	Name = "My Flower Shoop",
	Destroying = function()
		for key, connection in pairs(Connections) do
			if connection then
				connection:Disconnect()
			end
		end

		for key, enabled in pairs(Enableds) do
			Enableds[key] = false
		end
	end
})

Window:AddToggle({
	Text = "Auto Restock",
	Value = false,
	Flag = "restock_enabled",
	Callback = function(value)
		Enableds.Restock = value
		HandleRestock()
	end
})

Window:AddToggle({
	Text = "Auto Harvest",
	Value = false,
	Flag = "harvest_enabled",
	Callback = function(value)
		Enableds.Harvest = value
		HandleHarvest()
	end
})

Window:AddLabel("YouTube: Crokyreo")

--[[
-- auto plant --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.GrowingService.RF.PlantSeed
Event:InvokeServer(
    workspace.Plots.KopiPahitGamerPlot.Objects:GetChildren()[3],
    "Rose Seed",
    4
)

-- get seed info 
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MainMenu.Main.SeedsContent.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MainMenu.Main.SeedsContent.ScrollingFrame["Tulip Seed"].SeedName
]]
