local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")
local Character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()

local Enableds, Connections = {["Buy"] = false, ["Upgrade"] = false}, {}
local BuyParts, IncomeUIs = {},{}
local BuyButtonFolder = nil

local function FireTouch(hitPart, targetPart)
	if firetouchinterest then
		firetouchinterest(hitPart, targetPart, 1)
		task.wait()
		firetouchinterest(hitPart, targetPart, 0)
	end
end

local function FireButton(button)
	if firesignal then
		firesignal(button.Activated)
		firesignal(button.MouseButton1Click)
	end
end

local function GetPlot()
	local plots = workspace:FindFirstChild("Plots")
	if not plots then return nil end

	for _, plot in ipairs(plots:GetChildren()) do
		if plot and plot.Parent and plot.Name == LocalPlayer.Name then
			return plot
		end
	end

	return nil
end

local function FireHitbox(child)
	local hitbox = child:FindFirstChild("CollisionPart")
	if not hitbox then return end

	local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart") or Character:FindFirstChildWhichIsA("BasePart")
	if not rootPart  then return end

	FireTouch(rootPart, hitbox)
end

local function HandleBuy()
   if not Enableds.Buy then return end

   task.spawn(function()
       while Enableds.Buy do
		    for _, child in ipairs(BuyButtonFolder:GetChildren()) do
				if not Enableds.Buy then break end
				if not (child and child.Parent) then continue end
				FireHitbox(child)
			end
			task.wait(1)
		end
	end)
end

local function FireIncomeButton(child)
	if child.Name ~= "IncomeUI" then return end

	local upgradeButton = child:FindFirstChild("UpgBtn")
	if not upgradeButton then return end

	if Enableds["Upgrade"] then
		FireButton(upgradeButton)
	end

	--[[
		game:GetService("Players").LocalPlayer.PlayerGui.IncomeUI.UpgBtn
		game:GetService("Players").LocalPlayer.PlayerGui.IncomeUI.UpgBtn.ImageLabel
		80, 214, 255
		
		for i=1,1000 do
			task.wait()
			-- This code was generated by Cobalt
			-- https://github.com/notpoiu/cobalt

			local Event = game:GetService("ReplicatedStorage").Remotes.RequestUpgrade
			Event:FireServer(
				workspace.Plots[game:GetService("Players").LocalPlayer.Name].TycoonModel.Builds["Stage 1"]["Small Boat"]
			)
		end
	]]
end

local function OnIncomeButtonAdded(child)
	if child and child.Parent then
		if child.Name ~= "IncomeUI" then return end

		FireIncomeButton(child)
		IncomeUIs[child] = true
	end
end

Connections["CharacterAdded"] = LocalPlayer.CharacterAdded:Connect(function(newCharacter)
	Character = newCharacter
end)

local Plot = GetPlot()

if Plot then
	BuyButtonFolder = Plot:QueryDescendants("#TycoonModel > #BuyButtons")[1]
end

local Window = UI:CreateWindow({
	Name = "My Fishing Empire",
	Destroying = function()
		for key, value in pairs(Enableds) do
			Enableds[key] = false
		end
			
		for key, value in pairs(Connections) do
			if value then
				value:Disconnect()
			end
		end
	end
})

Window:AddToggle({
	Text = "Buy Button",
	Value = false,
	Flag = "buy_enabled",
	Callback = function(value)
		Enableds.Buy = value
		HandleBuy()
	end
})

Window:AddToggle({
	Text = "Upgrade Income",
	Value = false,
	Flag = "upgrade_enabled",
	Callback = function(value)
		Enableds["Upgrade"] = value
		if Connections["IncomeAdded"] then Connections["IncomeAdded"]:Disconnect() Connections["IncomeAdded"] = nil end
		if Connections["IncomeRemoved"] then Connections["IncomeRemoved"]:Disconnect() Connections["IncomeRemoved"] = nil end
		if value then 
			Connections["IncomeAdded"] = PlayerGui.ChildAdded:Connect(OnIncomeButtonAdded)

			Connections["IncomeRemoved"] = PlayerGui.ChildRemoved:Connect(function(child)
				IncomeUIs[child] = nil
			end)

			for _, child in ipairs(PlayerGui:GetChildren()) do
				if not Enableds["Upgrade"] then break end
				if not child or not child.Parent then IncomeUIs[child] = nil continue end
				OnIncomeButtonAdded(child)
			end

			if Enableds["Upgrade"] then
				task.spawn(function()
					while Enableds["Upgrade"] do
						task.wait(1)
						for child, value in pairs(IncomeUIs) do
							task.wait()
							if not Enableds["Upgrade"] then break end
							if not value or not child or not child.Parent then IncomeUIs[child] = nil continue end
							FireIncomeButton(child)
						end
					end
				end)
			end
		end
	end
})

Window:AddLabel({
	Text = "YouTube: Crokyreo",
	TextColor3 = Color3.fromRGB(255,255,255),
})
