local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")
local Character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()

local Enableds, Connections = {["Buy"] = false, ["Upgrade"] = false}, {}
local BuyButtonFolder = nil

Connections.CharacterAdded = LocalPlayer.CharacterAdded:Connect(function(newCharacter)
	Character = newCharacter
end)

local function FireTouch(hitPart, targetPart)
	if firetouchinterest then
		firetouchinterest(hitPart, targetPart, 1)
		task.wait()
		firetouchinterest(hitPart, targetPart, 0)
	end
end

local function FireButton(button)
	if firesignal then
		firesignal(button.Activated)
		firesignal(button.MouseButton1Click)
	end
end

local function GetPlot()
	local plots = workspace:FindFirstChild("Plots")
	if not plots then return nil end

	for _, plot in ipairs(plots:GetChildren()) do
		if plot and plot.Parent and plot.Name == LocalPlayer.Name then
			return plot
		end
	end

	return nil
end

-- Buy Function --
local function FireBuyButton(child)
	local hitbox = child:FindFirstChild("CollisionPart")
	if not hitbox then return end

	local rootPart = Character.PrimaryPart or Character:FindFirstChild("HumanoidRootPart") or Character:FindFirstChildWhichIsA("BasePart")
	if not rootPart  then return end

	FireTouch(rootPart, hitbox)
end

local function HandleBuy()
   if not Enableds.Buy then return end

   task.spawn(function()
       while Enableds.Buy do
		    for _, child in ipairs(BuyButtonFolder:GetChildren()) do
				if not Enableds.Buy then break end
				if not (child and child.Parent) then continue end
				FireBuyButton(child)
			end
			task.wait(0.5)
		end
	end)
end

-- Upgrade Function --
local function FireIncomeButton(child)
	if child.Name ~= "IncomeUI" then return end

	local upgradeButton = child:FindFirstChild("UpgBtn")
	if not upgradeButton then return end

	FireButton(upgradeButton)
end

local function HandleUpgrade()
   if not Enableds.Upgrade then return end

   task.spawn(function()
       while Enableds.Upgrade do
		    for _, child in ipairs(PlayerGui:GetChildren()) do
				if not Enableds.Upgrade then break end
				if not (child and child.Parent) then continue end
				FireIncomeButton(child)
			end
			task.wait(0.5)
		end
	end)
end

local Plot = GetPlot()

if Plot then
	BuyButtonFolder = Plot:QueryDescendants("#TycoonModel > #BuyButtons")[1]
end

local Window = UI:CreateWindow({
	Name = "My Fishing Empire",
	Destroying = function()
		for key, value in pairs(Enableds) do
			Enableds[key] = false
		end
			
		for key, value in pairs(Connections) do
			if value then
				value:Disconnect()
			end
		end
	end
})

Window:AddToggle({
	Text = "Buy Button",
	Value = false,
	Flag = "buy_enabled",
	Callback = function(value)
		Enableds.Buy = value
		HandleBuy()
	end
})

Window:AddToggle({
	Text = "Upgrade Income",
	Value = false,
	Flag = "upgrade_enabled",
	Callback = function(value)
		Enableds.Upgrade = value
		HandleUpgrade()
	end
})

Window:AddLabel({
	Text = "YouTube: Crokyreo",
	TextColor3 = Color3.fromRGB(255,255,255)
})

Window:AddLabel({
	Text = "Date: 07-17-2026",
	TextColor3 = Color3.fromRGB(255,255,255)
})

-- Game Info --
--[[
		game:GetService("Players").LocalPlayer.PlayerGui.IncomeUI.UpgBtn
		game:GetService("Players").LocalPlayer.PlayerGui.IncomeUI.UpgBtn.ImageLabel
		80, 214, 255
		
		for i=1,1000 do
			task.wait()
			-- This code was generated by Cobalt
			-- https://github.com/notpoiu/cobalt

			local Event = game:GetService("ReplicatedStorage").Remotes.RequestUpgrade
			Event:FireServer(
				workspace.Plots[game:GetService("Players").LocalPlayer.Name].TycoonModel.Builds["Stage 1"]["Small Boat"]
			)
		end
]]
