local CodeThread = nil

workspace.AnakPox1.Nametag.Enabled = false

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.Fishing
Event:FireServer(
    CFrame.new(-309.3076171875, 9.7615242004395, 106.26274871826, -0.15476256608963, -4.7383696966108e-08, 0.98795169591904, -2.7558765935964e-08, 1, 4.3644472924598e-08, -0.98795169591904, -2.0472198158927e-08, -0.15476256608963)
)

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.FishingMinigame
firesignal(Event.OnClientEvent, 
    nil,
    nil,
    "586c9af7-45fb-4c2f-8f7c-6f8a7ef8dec0"
)

-- click --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.UpdateFishProgression
Event:FireServer()

game:GetService("Players").LocalPlayer.PlayerGui.MainGui.Fishing
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.Fishing.BarFrame.Bar -- 0.45 - 0.55
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.Mobile.Fishing


-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.FishingMinigame
Event:FireServer(
    false,
    "c8f5cc50-8f33-493f-ae9f-99212569bf2b"
)

-- auto sell all --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.SellFish
Event:FireServer(
    "All"
)

-- claim all codes --
game:GetService("ReplicatedStorage").Data
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Events.RedeemCode
Event:FireServer(
    "ThanksForNitroBoost"
)
game:GetService("ReplicatedStorage").Data["11045366881"].Code
