-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.Events.ClickRemote
Event:FireServer()




game:GetService("Players").LocalPlayer.PlayerGui.MainGui.RebirthMenu
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.RebirthMenu.ProgressBar.BarFill
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.RebirthMenu.RebirthButton


game:GetService("Players").LocalPlayer.PlayerGui.MainGui.UpgradesMenu.UpgradeScrollFrame
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.UpgradesMenu.UpgradeScrollFrame["Aura Luck"].BuyWinButton
game:GetService("Players").LocalPlayer.PlayerGui.MainGui.UpgradesMenu.UpgradeScrollFrame["Aura Luck"].UpgradeName.Text
