local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Crokier/Roblox/main/Packages/Sampluy/init.luau"))()

local Services = setmetatable({}, {__index = function(_, i) return cloneref and cloneref(game:GetService(i)) or game:GetService(i) end})
local Players = Services.Players
local ReplicatedStorage = Services.ReplicatedStorage

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChildOfClass("PlayerGui")
local Backpack = LocalPlayer:FindFirstChildOfClass("Backpack")
local Character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()

local AnxietyFill = PlayerGui:QueryDescendants("#StatGui > #Anxiety > #AnxietyBarClip > #AnxietyBar")[1]
local Enableds = {["Anxiety"] = false, ["AnxietyDebounce"] = false}
local Cacheds = {}

local Packets = {
  ToolAction = ReplicatedStorage:QueryDescendants("#ToolEvents > #ToolAction")[1]
}

local function Cleanup(object)
	local objectType=typeof(object)
	if objectType=='function' then
		pcall(function() object() end)
	elseif objectType=='RBXScriptConnection' then
		object:Disconnect()
	elseif objectType=='Instance' then
		if object and object.Parent then object:Destroy() end
	elseif objectType=='thread' then
		local wasCancelled:boolean?=nil
		if coroutine.running()~=object then
			wasCancelled=pcall(function()
				task.cancel(object)
			end)
		end
		if not wasCancelled then
			local toClean=object
			task.defer(function()
				task.cancel(toClean)
			end)
		end
	elseif objectType=='table' then
		for i,k in ipairs(GENERIC_OBJECT_CLEANUP_FUNCS) do
			local func=object[k]
			if typeof(func)=='function' then
				pcall(func)
				break
			end
		end
	end
	return nil
end

Cacheds.CharacterAdded = LocalPlayer.CharacterAdded:Connect(function(newCharacter)
	Character = newCharacter
end)

local function IsNPC(instance)
	return instance and instance:IsA("Model") and instance:FindFirstChildOfClass("Humanoid") and not Players:GetPlayerFromCharacter(instance)
end


Cacheds.NPCAdded = workspace.ChildAdded:Connect(function(npc)
	if newCharacter.Name == "Teacher" and IsNPC(npc) then
		
	end
end)

--[[
-- auto cheat --
-- Take photo

local Event = game:GetService("ReplicatedStorage").ToolEvents.ToolAction
Event:FireServer(
    "Phone1",
    "Use"
)

-- View answer 
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").ToolEvents.ToolAction
Event:FireServer(
    "Phone1",
    "SecondUse"
)

workspace.Teacher -- NPC

game:GetService("Players").LocalPlayer.Backpack.Phone1
game:GetService("Players").LocalPlayer.Backpack.Phone1.Phone.Screen.SurfaceGui.Frame.AnswersText
]]

local function HandleCheat()
	if not Enableds.Cheat then return end

	task.spawn(function()
		while Enableds.Cheat do
			task.wait()
		end
	end)
end

local function FireAnxiety()
  if Enableds.Anxiety and AnxietyFill.Size.X.Scale >= 0.5 then
     if not Enableds.AnxietyDebounce then
        Enableds.AnxietyDebounce = true 

        repeat
            local tool = Backpack:FindFirstChild("Pencil")
            if tool then
               local humanoid = Character:FindFirstChildOfClass("Humanoid")
               if humanoid then
                  humanoid:EquipTool(tool)
               end
            end
            task.wait(1)
         until not Enableds.Anxiety or AnxietyFill.Size.X.Scale < 0.1
         
         Enableds.AnxietyDebounce = false
      end
   end
end

local function HandleAnxiety()
   if not Enableds.Anxiety then Enableds.AnxietyDebounce = false return end
   task.spawn(function()
      while Enableds.Anxiety do
         FireAnxiety()
         task.wait()
      end
   end)
end

local Window = UI:CreateWindow({
	Name = "Cheating During Testing",
	Destroying = function()
        for key, enabled in pairs(Enableds) do
		    Enableds[key] = false
        end
		for key, object in pairs(Cacheds) do
			if object then
				Cleanup(object)
			end
		end
	end
})

Window:AddToggle({
	Text = "Auto Anxiety",
	Value = false,
	Flag = "anxiety_enabled",
	Callback = function(value)
		Enableds.Anxiety = value
		HandleAnxiety()
	end
})

Window:AddLabel({
	Text = "YouTube: Crokyreo",
	TextColor3 = Color3.fromRGB(255, 255, 255)
})
