-- auto cheat --
-- Take photo

local Event = game:GetService("ReplicatedStorage").ToolEvents.ToolAction
Event:FireServer(
    "Phone1",
    "Use"
)

-- View answer 
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").ToolEvents.ToolAction
Event:FireServer(
    "Phone1",
    "SecondUse"
)

game:GetService("Players").LocalPlayer.Backpack.Phone1
game:GetService("Players").LocalPlayer.Backpack.Phone1.Phone.Screen.SurfaceGui.Frame.AnswersText

-- auto anxiety --
game:GetService("Players").LocalPlayer.Backpack.Pencil
game:GetService("Players").LocalPlayer.PlayerGui.StatGui.Anxiety.AnxietyBarClip.AnxietyBar
