-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Packets.Packet.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Packets.Packet.RemoteEvent
Event:FireServer(
    buffer.fromstring("\f(")
)




-- Collect
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Packets.Packet.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Packets.Packet.RemoteEvent
Event:FireServer(
    buffer.fromstring("\v)")
)


-- Deposit Simulator --

game:GetService("Players").LocalPlayer.Ekwipunek

getgenv().removingActive = not getgenv().removingActive 
while getgenv().removingActive do
task.wait(1)
-- Cached Event Path: ReplicatedStorage.RemoveLastBottle
local Event = game:GetService("ReplicatedStorage").RemoveLastBottle
Event:FireServer()
end

-- Lick a Brainrot --
-- Collect Cash --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Remotes.Claim
local Event = game:GetService("ReplicatedStorage").Remotes.Claim
Event:InvokeServer(
    1
)


-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Main.Screens.Rebirth.Buttons.Rebirth

-- Auto Train --
game:GetService("Players").LocalPlayer.PlayerGui.Main.doubleButton
game:GetService("Players").LocalPlayer.Backpack.Gym
workspace.KopiPahitGamer.Gym
