-- Clean Crew --
-- ESP Monster --
workspace.MonsterContainer


-- Build a Slime Defense --

-- Auto Upgrade --
workspace.Map.Plots.Plot2.Main.Plot.Structures["8eb72611-efc2-4a35-a816-51254ec54ba3"]
Plot is Owner string 

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Remotes.Plot.Building
local Event = game:GetService("ReplicatedStorage").Remotes.Plot.Building
Event:InvokeServer(
    "UpgradeStructure",
    "8eb72611-efc2-4a35-a816-51254ec54ba3"
)

game:GetService("ReplicatedStorage").Remotes.Plot.UpgradeKing:InvokeServer()


-- Auto Attack --
workspace.Map.Plots.Plot2.Npcs



-- Farm a Fish --
workspace.Ponds:GetChildren()[4].Buildings
no ownership use Target Instance
workspace.Ponds:GetChildren()[4].Buildings["c1b67f35-fa1c-4be9-8d38-0e388a29515d"]
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.rbxts_include.node_modules.@rbxts.remo.src.container.bait.collectAllFish
local Event = game:GetService("ReplicatedStorage").rbxts_include.node_modules["@rbxts"].remo.src.container["bait.collectAllFish"]
Event:FireServer(
    "c1b67f35-fa1c-4be9-8d38-0e388a29515d"
)

Collect Fish ^



-- auto sell
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.rbxts_include.node_modules.@rbxts.remo.src.container.sellFish.sellAllFish
local Event = game:GetService("ReplicatedStorage").rbxts_include.node_modules["@rbxts"].remo.src.container["sellFish.sellAllFish"]
Event:FireServer()



-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Packets.Packet.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Packets.Packet.RemoteEvent
Event:FireServer(
    buffer.fromstring("\f(")
)




-- Collect
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Packages.Packets.Packet.RemoteEvent
local Event = game:GetService("ReplicatedStorage").Packages.Packets.Packet.RemoteEvent
Event:FireServer(
    buffer.fromstring("\v)")
)


-- Deposit Simulator --

game:GetService("Players").LocalPlayer.Ekwipunek

getgenv().removingActive = not getgenv().removingActive 
while getgenv().removingActive do
task.wait(1)
-- Cached Event Path: ReplicatedStorage.RemoveLastBottle
local Event = game:GetService("ReplicatedStorage").RemoveLastBottle
Event:FireServer()
end

-- Lick a Brainrot --
-- Collect Cash --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Remotes.Claim
local Event = game:GetService("ReplicatedStorage").Remotes.Claim
Event:InvokeServer(
    1
)


-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Main.Screens.Rebirth.Buttons.Rebirth

-- Auto Train --
game:GetService("Players").LocalPlayer.PlayerGui.Main.doubleButton
game:GetService("Players").LocalPlayer.Backpack.Gym
workspace.KopiPahitGamer.Gym
