



-- Lick a Brainrot --
-- Collect Cash --
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

-- Cached Event Path: ReplicatedStorage.Remotes.Claim
local Event = game:GetService("ReplicatedStorage").Remotes.Claim
Event:InvokeServer(
    1
)


-- Auto Rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Main.Screens.Rebirth.Buttons.Rebirth

-- Auto Train --
game:GetService("Players").LocalPlayer.PlayerGui.Main.doubleButton
game:GetService("Players").LocalPlayer.Backpack.Gym
workspace.KopiPahitGamer.Gym
