-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.CodesService.RF.Redeem
Event:InvokeServer(
    "NIE"
)
print(require(game:GetService("ReplicatedStorage").Shared.Config.CodesConfig).Codes)

