
-- Upgrade --
game:GetService("Players").LocalPlayer.PlayerGui.Main.UIFrames.UpgradeFrame.ScrollingFrame.PlayerWalkspeed

local Event = game:GetService("ReplicatedStorage").Remotes.BuyUpgrade
Event:FireServer(
    "SpawnSpeed"
)

game:GetService("Players").LocalPlayer.PlayerGui.Main.UIFrames.UpgradeFrame.ScrollingFrame.CapacityLimit.BuyButton
game:GetService("Players").LocalPlayer.PlayerGui.Main.UIFrames.UpgradeFrame.ScrollingFrame.CapacityLimit.BuyButton.TextLabel.Text == "Not Enough"
game:GetService("Players").LocalPlayer.PlayerGui.Main.UIFrames.UpgradeFrame.ScrollingFrame.CapacityLimit.TextLabel



-- Rebirth --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.BuyRebirth
Event:FireServer()


-- Claim Index --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.ClaimIndexReward
Event:FireServer(
    "Pizza"
)

game:GetService("Players").LocalPlayer.PlayerGui.Main.UIFrames.IndexFrame.ViewFrame.ClaimFrame.ClaimAlllButton

