-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

workspace.Drops
local Event = game:GetService("ReplicatedStorage").Remotes.DropPickup
Event:FireServer(
    147866 -- workspace.Drops.Drop_148007
)

-- merge --
workspace.Tycoon.Tycoons.D.Buttons.Merge.Head

-- deposit --
workspace.Tycoon.Tycoons.D.Buttons.Deposit.Head


-- collect cash --
workspace.Tycoon.Tycoons.D.Buttons.Cashier.Head

-- upgrade --
workspace.Tycoon.Tycoons.D.Buttons.Upgrade.Head

-- buy hasmter --
workspace.Tycoon.Tycoons.D.Buttons.(Add1,Add5,Add25,Add100).Head
