-- Collect Cash --
local Event = game:GetService("ReplicatedStorage").Events.Global.Core.TurretCollect
Event:FireServer()

-- auto upgrade --
game:GetService("Players").LocalPlayer.PlayerGui.PlotScreens.TurretScreen.Frame.TurretLuck.Buy
game:GetService("Players").LocalPlayer.PlayerGui.PlotScreens.TurretScreen.Frame.TurrentSlots.Buy.BackgroundColor3 == Color3.new(50, 214, 0)

game:GetService("Players").LocalPlayer.PlayerGui.PlotScreens.ZombieScreen.Frame.ZombieLuck.Buy
game:GetService("Players").LocalPlayer.PlayerGui.PlotScreens.ZombieScreen.Frame.ZombieYield.Buy

workspace.Plots.Plot4 --  OwnerUserId
workspace.Plots.Plot4.Turrets["Spud Gun"] -- GridCell Attribute
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.Global.Core.TurretUpgrade
Event:FireServer(
    "Grid3"
)
