getgenv().Train = not getgenv().Train
 while getgenv().Train do 
task.wait(1)
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").PetSystem.EggRemoteEvents.KickBall
Event:FireServer(
    100
)
 end

-- rebirth --
game:GetService("Players").LocalPlayer.PlayerGui.Main.RebirthFrame
game:GetService("Players").LocalPlayer.PlayerGui.Main.RebirthFrame.ProgressBar.CanvasGroup.Fill
game:GetService("Players").LocalPlayer.PlayerGui.Main.RebirthFrame.Rebirth

--  buy trail --
game:GetService("Players").LocalPlayer.PlayerGui.Main.TrailsFrame.CanvasGroup.ScrollingFrame
game:GetService("Players").LocalPlayer.PlayerGui.Main.TrailsFrame.CanvasGroup.ScrollingFrame.Cyan.Locked
