-- Home --
workspace["玩家的商店"]["10952058440"].Root

workspace.TowerFolder
workspace.TowerFolder.Center_2.Door["门"].Root.DoorHpUi.HPBar.Bar
workspace.TowerFolder.Center_2.NpcSpawn
workspace.TowerFolder.TowerBase -- this origin tower

workspace.TowerFolder.TowerBase.RescueNpc_90102_1 -- SpawnKey: 2_2
workspace.TowerFolder.Center_1.RescueNpc_90202_2

-- Pickup npc --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Msg.RemoteEvent.NetWorkRemoteEvent
Event:FireServer(
    "NPC\xE6\x95\x91\xE6\x8F\xB4\xE7\x99\xBB\xE8\xAE\xB0",
    "2_2"
)
local Event = game:GetService("ReplicatedStorage").Msg.RemoteEvent.NetWorkRemoteEvent
Event:FireServer(
    "NPC\xE6\x95\x91\xE6\x8F\xB4\xE7\x99\xBB\xE8\xAE\xB0",
    "1_2"
)

-- attack door --
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").Msg.RemoteEvent.NetWorkRemoteEvent
Event:FireServer(
    "\xE9\x94\xA4\xE5\xAD\x90\xE7\xA0\xB8\xE9\x97\xA8",
    workspace.TowerFolder.Center_1.Door["\233\151\168"].Root
)
