-- loadstring(game:HttpGet("https://raw.githubusercontent.com/PaazlisMaswa/RobloxProject/refs/heads/main/Packages/Mercury/ExampleMercury.lua"))()
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/PaazlisMaswa/RobloxProject/refs/heads/main/Packages/Mercury/init.luau"))()
local Window = Library:Create({Theme = Library.Themes.Serika})
local Tab = Window:Tab({Icon = "rbxassetid://6034996695",Name = "Aimbot"})
local Label = Tab:Label({Name = "Selemat datang di aimbot",Description = "Kegunaan untuk mentarget yang terdekat pemain"})
